package eu.ydp.empiria.player.client.controller.events.delivery;

public enum DeliveryEventType {
	RESET, CONTINUE, CHECK, LOCK, UNLOCK, SHOW_ANSWERS, HIDE_ANSWERS, 
	ASSESSMENT_LOADING, ASSESSMENT_LOADED, ASSESSMENT_STARTED,
	PAGE_CHANGING, PAGE_UNLOADING, PAGE_UNLOADED, PAGE_LOADING,
	TEST_PAGE_LOADED, TOC_PAGE_LOADED, SUMMARY_PAGE_LOADED,
	STATE_CHANGED, FEEDBACK_SOUND;
}
