package eu.ydp.empiria.player.client.util.events.dragdrop;

public enum DragDropEventTypes {
	DRAG_START, DRAG_END, DRAG_CANCELL, REGISTER_DROP_ZONE, DISABLE_DROP_ZONE, ENABLE_ALL_DROP_ZONE,
	USER_CHANGE_DROP_ZONE, FIND_VALUE_IN_SOURCELIST, VALUE_FOUND_IN_SOURCELIST, VALUE_NOT_FOUND_IN_SOURCELIST
}
