package eu.ydp.empiria.player.client.util.events.media;

public enum MediaEventTypes {
	PLAY, ON_PLAY, STOP, ON_STOP, PAUSE, ON_PAUSE, CHANGE_VOLUME, ON_VOLUME_CHANGE,
 ERROR, ON_ERROR, ENDED, ON_DURATION_CHANGE, SET_CURRENT_TIME, ON_TIME_UPDATE, MUTE, ON_END,
 MEDIA_ATTACHED, TEXT_TRACK_UPDATE
}
