package eu.ydp.empiria.player.client.util.events.media;

public enum MediaEventTypes {
	PLAY, PLAY_LOOPED, ON_PLAY, STOP, ON_STOP, PAUSE, ON_PAUSE, RESUME, CHANGE_VOLUME, ON_VOLUME_CHANGE, ERROR, ON_ERROR, ENDED, ON_DURATION_CHANGE, SET_CURRENT_TIME, ON_TIME_UPDATE, MUTE, ON_END, MEDIA_ATTACHED, TEXT_TRACK_UPDATE, ON_FULL_SCREEN_OPEN, ON_MOBILE_FULL_SCREEN_OPEN, ON_FULL_SCREEN_EXIT, ON_FULL_SCREEN_SHOW_CONTROLS, ON_LOADED_DATA, CAN_PLAY, WAITING, SUSPEND;
}
