package eu.ydp.empiria.player.client.util.events.internal.player;

public enum PlayerEventTypes {
    CREATE_MEDIA_WRAPPER,
    TOUCH_EVENT_RESERVATION,
    ASSESSMENT_LOADED,
    ASSESSMENT_STARTING,
    ASSESSMENT_STARTED,
    BEFORE_FLOW,
    LOAD_PAGE_VIEW,
    PAGE_UNLOADED,
    PAGE_LOADED,
    PAGE_CHANGE,
    PAGE_REMOVED,
    PAGE_CHANGING,
    PAGE_VIEW_LOADED,
    PAGE_INITIALIZING,
    PAGE_INITIALIZED,
    PAGE_SWIPE_STARTED,
    PAGE_CONTENT_GROWN,
    PAGE_CONTENT_DECREASED,
    PAGE_CHANGE_STARTED,
    PAGE_CREATED_AND_STARTED,
    SLIDESHOW_STARTED,
    TEST_PAGE_LOADED,
    WINDOW_RESIZED;
}
