package eu.ydp.empiria.player.client.util.events.player;

public enum PlayerEventTypes {
	CREATE_MEDIA_WRAPPER, 
	TOUCH_EVENT_RESERVATION,
	ASSESSMENT_LOADED, 
	ASSESSMENT_STARTING,
	ASSESSMENT_STARTED, 
	BEFORE_FLOW, 
	AFTER_FLOW, 
	LOAD_PAGE_VIEW, 
	PAGE_UNLOADED, 
	PAGE_LOADED, 
	PAGE_CHANGE, 
	PAGE_REMOVED, 
	PAGE_CHANGING,
	PAGE_VIEW_LOADED,
	PAGE_INITIALIZING, 
	PAGE_INITIALIZED,
	PAGE_SWIPE_STARTED,
	PAGE_CONTENT_RESIZED,
	PAGE_CHANGE_STARTED, 
	TEST_PAGE_LOADED;
}
