package eu.ydp.empiria.player.client.util.events.player;

public enum PlayerEventTypes {
	CREATE_MEDIA_WRAPPER, PAGE_UNLOADED, PAGE_LOADED, TOUCH_EVENT_RESERVATION,
	PAGE_CHANGE, PAGE_REMOVED, PAGE_CHANGING, ASSESSMENT_LOADED, ASSESSMENT_STARTING,
	BEFORE_FLOW, ASSESSMENT_STARTED, AFTER_FLOW, LOAD_PAGE_VIEW, PAGE_VIEW_LOADED,
	PAGE_INITIALIZING, PAGE_INITIALIZED,PAGE_SWIPE_STARTED
}
